const { createHmac,randomBytes} = require('crypto');         // import crypto hash   // built in package
const { create } = require('domain');

const { Schema, model} = require("mongoose");
const { createTokenForUser } = require('../services/authentication');

const userSchema = new Schema({
    fullName: {
        type:String,
        required:true,
    },
    email: {
        type:String,
        required:true,
        unique: true,
    },
    salt: {
        type: String,
        
    },
    password: {
        type: String,
        required:true,
    },
    profileImageURL: {
        type: String,
        default:"/images/default.png",
    },
    role: {
        type: String,
        enum: ["USER", "ADMIN"],
        default: "USER",
    },
}, 
{timestamps: true}
);

// mongoosh middleware.

// userSchema.pre("save", function (next){   //this is a middleware in Mongoose, specifically a pre-save hook that runs before a document is saved.       // ye function password ko hash kar dega.
//     const user = this;
//     if (!user.isModified("password")) return;

//     const salt = randomBytes(16).toString();    // isko ham salt bana rhe hia   ; ye ek random string hai .  // yaha ham documentation wlaa secret key random genrate kar rhe hai.   // har user ki apani pani random secret key generate hogi.
//     const hashedPassword = createHmac('sha256', salt)      //hash kar rhe hai ; ham yaha sha256 algorithm use kar rhe hai   // (algo , key ); key is your slat thats generated by random
//         .update(user.password)
//         .digest("hex");
//     this.salt = salt;
//     this.password = hashedPassword;

//     next();
// });

//signup
userSchema.pre("save", function () {    // presave means : Before a User document is saved into MongoDB, run this function first.
    const user = this;

    if (!user.isModified("password")) return;

    const salt = randomBytes(16).toString("hex");     //A salt is a random value added to the hashing process.salt makes password hashes harder to attack.

    const hashedPassword = createHmac("sha256", salt)   //password + salt ->   SHA-256 -hash value
        .update(user.password)
        .digest("hex");

    user.salt = salt;
    user.password = hashedPassword;
});

//signin
userSchema.static('matchPasswordAndGenerateToken',async function(email, password){
    const user = await this.findOne({email});
    if(!user) throw new Error("User not found!");

    const salt = user.salt;
    const hashedPassword = user.password;    // signup ke waqt ka hashPassword

    const userProvidedHash = createHmac("sha256",salt)    // jo user login ke waqt pass de rha usko hash kar rhe hai.
    .update(password)
    .digest("hex");

    if(hashedPassword !== userProvidedHash)
      throw new Error("Incorrect Password");

    //return { ...user._doc ,password:undefined, salt: undefined};    // else ham user object ko return kar denge.
    //return user;

    const token = createTokenForUser(user);
    return token;
});










// user.isModified("password") checks if the password field was changed.
// - When creating a new user → password is considered modified.
// - When updating only other fields (like email or name) → password is not modified.
// The "!" means NOT, so (!user.isModified("password")) means the password was NOT changed.
// In that case, we skip hashing and return early to avoid re-hashing an unchanged password.







//we need a model.

const User = model('user', userSchema);
module.exports = User;










// Now the generated salt is stored in the user's document.

// Your database might conceptually look like:

// {
//     email: "satyam@gmail.com",
//     password: "8f4a...hashed...",
//     salt: "abc789..."
// }